data:
  env: localhost-online
  user:
    username: fengzheng-online
    password: password-online
    
spring:
  application:
    name: config-single-client
  profiles:
    activ: dev

server:
  port: 8081
