data:
  env: localhost-dev-edit888
  user:
    username: fengzheng-dev999
    password: password-dev

spring:
  application:
    name: config-single-client
  profiles:
    activ: dev

server:
  port: 8081