data:
  env: localhost-dev-edit888
  user:
    username: fengzheng-dev999
    password: password-dev1

spring:
  application:
    name: config-single-client
  profiles:
    activ: dev

server:
  port: 8081

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
